### ISSUE TITLE
Bootstrap '.table-responsive' Compatibility?

### ISSUE THREAD

**Issue by saintplay** [Amphiluke/floating-scroll#1]
This is not working for some reason when my container is a table-responsive from bootstrap

https://jsfiddle.net/djap96/c0ne9eu0/1/

**Comment by Amphiluke** [comment]
Hi,

To make the floatingScroll plugin work it's required to include [jquery.floatingscroll.css](https://github.com/Amphiluke/floating-scroll/blob/master/src/jquery.floatingscroll.css) on the page. Once you do it, your fiddle will start working.

**Comment by saintplay** [comment]
So simple, worked in production as well, thanks for the nice plugin and for the quick response.
