### ISSUE TITLE
Floating scroll bar "add fl-scrolls-hidden" class when i minimize browser windows and refresh it?

### ISSUE THREAD

**Issue by hntvip** [Amphiluke/floating-scroll#14]
As in title's describle,  When i resize the bowser and it add " fl-scrolls-hidden" class, it does not show scrollbar when its owner class has added: bottom: 9999px;

**Comment by Amphiluke** [comment]
I’m afraid I didn’t catch the way to reproduce the bug. Could you please describe it in more details (step-by-step)? Or it would be even better if you provided a simple demo using [JSFiddle](https://jsfiddle.net/) and [RawGit](https://rawgit.com/). Thanks.

**Comment by hntvip** [comment]
Thank  @Amphiluke a lot , I think I fixed it. I set timeout function when resizing a browser
