### ISSUE TITLE
Import warning

### ISSUE THREAD

**Issue by dennisc9** [Amphiluke/floating-scroll#15]
I have installed floatingScroll via npm. v3.0.2

I then attempt to import into my vue application: 
`import floatingScroll from "floating-scroll";`

I then get this warning, not an error: 
> ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./test.vue 156:20-34 "export 'default' (imported as 'floatingScroll') was not found in 'floating-scroll'

I am still achieving the floating scroll i am looking for, but i would like to tackle this warning and make sure that isn't a precursor to something breaking in the fiture.

**Comment by Amphiluke** [comment]
Hi @dennisc9,

Actually floatingScroll (when used as a module) exports nothing. This is a jQuery plugin and so it just extends jQuery’s prototype (`jQuery.fn`). If you want to use the plugin as an ES module, import it as any other module which has no exported value:

```javascript
import "floating-scroll";
```
