### ISSUE TITLE
how use in vuejs ? 

### ISSUE THREAD

**Issue by khanhnam99** [Amphiluke/floating-scroll#18]
npm i floating-scroll

------------------------
import floating-scroll from "floating-scroll";

how use it  in  html?

i use es6

**Comment by Amphiluke** [comment]
Hello, @khanhnam99,

floating-scroll is a jQuery plugin. I wouldn’t recommend using it in a Vue-based application (unless you really want jQuery to be a dependency of your project). Instead, you could integrate [handy-scroll](https://github.com/Amphiluke/handy-scroll) in your app. It is a _dependency-free_ analog of floating-scroll. Note however that neither handy-scroll is fully adapted to the Vue ecosystem. You will need to explicitly initialize the widget somewhere in your Vue app instance or a component (e.g. in the [mounted](https://vuejs.org/v2/api/#mounted) hook). I’ve assembled a simple live demo for “handy-scroll+Vue” integration, you can check it out [here](https://codepen.io/amphiluke/pen/vYYoeaz).

I’m currently developing a full-fledged Vue.js component for handy-scroll: [vue-handy-scroll](https://github.com/Amphiluke/vue-handy-scroll). It is not completed yet, so I suggest using [handy-scroll](https://github.com/Amphiluke/handy-scroll) until this Vue.js component is finally published on npm.

**Comment by khanhnam99** [comment]
import handyScroll from 'handy-scroll';

how use it  ?

**Comment by Amphiluke** [comment]
Just check out the [live example](https://codepen.io/amphiluke/pen/vYYoeaz) I have provided.

Implement the hook `mounted` and place widget initialization there.

```javascript
mounted() {
  this.$nextTick(() => {
    handyScroll.mount(this.$refs.scrollable);
  });
}
```

`this.$refs.scrollable` is just a reference to the container which you want to apply the scroll bar to. You might have noticed the `ref` attribute in the template:

```html
<div class="my-container" ref="scrollable">
```
