### ISSUE TITLE
Plugin does not support option for floating vertical scrollbars

### ISSUE THREAD

**Issue by dashrendar2112** [Amphiluke/floating-scroll#19]
The jQuery plugin works great with a floating horizontal scroll bar.

Would it be possible to add support for a floating vertical scrollbar via an "option" or "setting"?

**Comment by Amphiluke** [comment]
Hello, @dashrendar2112 

Specifying the desired scrollbar orientation is now available. The feature has been released in [v3.1.0](https://github.com/Amphiluke/floating-scroll/releases/tag/v3.1.0). Please refer the docs (the sections [“Initialisation”](https://github.com/Amphiluke/floating-scroll#initialisation) and [“Auto-initialisation”](https://github.com/Amphiluke/floating-scroll#auto-initialisation)) for more details.

[Here is also a Pen](https://codepen.io/amphiluke/pen/vYOGmYO) demonstrating this new feature live.
