### ISSUE TITLE
Floating scroll bars do not work on Safari

### ISSUE THREAD

**Issue by Amphiluke** [Amphiluke/floating-scroll#6]
Issue by @wesley-kiyohara
Originally opened on 24 Sep 2015 as Amphiluke/jquery-plugins#7

---

> Currently on Safari, I am unable to see the horizontal scrollbar until the bottom the div is reached. This is after I've changed my Mac settings to always display scrollbars, and can be seen on each of your demos. Although I cannot see the .fl-scrolls div, I'm still able to hover over where it should be and scroll horizontally.
> ![scroll](https://cloud.githubusercontent.com/assets/7770422/10062404/29e2c1fe-6217-11e5-8c9a-765ea4799a19.gif)

**Comment by kristenarmes** [comment]
Hi Amphiluke, thank you for this plugin, it has been great for me using it on Chrome and Firefox. I have noticed in my use case I am running into this exact issue that was reported a couple years ago. I have Safari v11.1 and I can see that the scrollbar is there in the HTML, but it is invisible as this other user reported. I also checked out your demos in Safari, and they are also not working.

**Comment by Amphiluke** [comment]
Hello Kristen,
Thank you for the notice. I will check this at my earliest convenience. It is possible that the previously found solution is no longer valid in the newest Safari versions.

**Comment by Amphiluke** [comment]
I managed to fix the issue (again :D).

@kwetts 
Kristen, could you please look at the [demo page](https://amphiluke.github.io/floating-scroll/?v3.0.2) again and check whether it’s OK now in Safari? Please make sure to reload it without browser cache. I tested in Safari v11.1, but it would be great if you also confirmed that the bug is not reproduced for you anymore. After that I will publish the new version of the plugin to npm. Thanks.

**Comment by kristenarmes** [comment]
Just checked out the demo page and the scrollbar does work for me now in Safari. Thanks so much for your quick response/fix!

**Comment by Amphiluke** [comment]
Released as [v3.0.2](https://github.com/Amphiluke/floating-scroll/releases/tag/v3.0.2). The new plugin version is also available on npm.
